### ISSUE TITLE
Allow modifying the marshaled message to support assorted root level fields

### ISSUE THREAD

**Issue by deefdragon** [go-extras/elogrus#5]
elogrus currently puts all but a few fields inside a `data.` prefix. There are some fields that I wish to log that require being root level (such as a `trace.id` field).

I suggest adding a callback to the hook object that, in createMessage, can get called to modify the message object which is marshaled into json. 

This would require createMessage returning an any or map[string]any. createMessage is only consumed by json.Marshal so changing it should be fine. 

```go
type ModifyMessage func(entry *logrus.Entry, message elogrus.Message) any
```

**Comment by denisvmedia** [comment]
Hi! Thank you for your proposal. Do you mind submitting a draft PR to illustrate the idea?

**Comment by deefdragon** [comment]
PR created.

**Comment by denisvmedia** [comment]
Thank you @deefdragon . I've just merged your PR.
