### ISSUE TITLE
Elastic Search v8

### ISSUE THREAD

**Issue by partomatl** [go-extras/elogrus#7]
Hi @denisvmedia!

Could you please create a v8 branch?

Thanks!

**Comment by denisvmedia** [comment]
Check please, if it works for you now.

**Comment by partomatl** [comment]
Thanks!

There is a bug in `asyncFireFunc` due to this line of code:
https://github.com/go-extras/elogrus/blob/8a20da4ef916ce7c809fe19d5e1ad3d7ed8dfe97/hook.go#L176

Indeed, the `Dup()` method in the `logrus` package does not duplicate the `Message`, `Level` and `Caller` fields:
https://github.com/sirupsen/logrus/blob/f8bf7650dccb756cea26edaf9217aab85500fe07/entry.go#L81-L87

In `logrus`, `Dup()` is only used here, and just after that those three fields are set:
https://github.com/sirupsen/logrus/blob/f8bf7650dccb756cea26edaf9217aab85500fe07/entry.go#L224-L240

Therefore, when using `asyncFireFunc`, the `Level` and `Message` fields are lost: `Level` is always `panic` and `Message` is always omitted (because it's empty). The field `Caller` is also lost.

Also, what do you think about using the [official ECS library](https://www.elastic.co/guide/en/ecs-logging/go-logrus/current/intro.html) for `logrus` (https://github.com/elastic/ecs-logging-go-logrus) to log to Elastic using the [ECS logging format](https://www.elastic.co/guide/en/ecs-logging/overview/current/intro.html)?

**Comment by denisvmedia** [comment]
Yeah, nice spot. I changed it the other way. Hopefully, it's now better. Probably, I need to improve the tests to catch this issue earlier.

As for the ECS logging format. We have a way to modify the message before pushing it to ES. See: https://github.com/go-extras/elogrus/blob/master/hook.go#L48. You can set it to something like (note, I wrote it here, without testing):

```go
formatter := &ecslogrus.Formatter{}
hook.MessageModifierFunc = func(entry *logrus.Entry, message *Message) any {
    var data json.RawMessage
    data, err := formatter.Format(entry)
    if err != nil {
        // decide how to handle
        return entry // unmodified entry to preserve it
    }
    return data
}
```

This way you can use the official ECS library together with `go-extras/elogrus`.

**Comment by partomatl** [comment]
Thanks for the fix 😃 

I don't think we can use a `MessageModifierFunc` as is, because `ecslogrus.Formatter` implements the `logrus.Formatter` interface. Therefore, calling `formatter.Format(entry)` in a `MessageModifierFunc` already marshals the entry as JSON.
As the output value of a `ModifyMessageFunc` it then marshaled as JSON, the entry will be marshaled twice (resulting in a `400 Bad Request` at the Elastic level).

**Comment by denisvmedia** [comment]
`ecslogrus.Formatter` indeed implements `logrus.Formatter`, and that's why I used its function `formatter.Format(entry)` that will produce `[]byte`, which - when assigned to `data` of `json.RawMessage` type - will produce raw json bytes that won't be double marshaled due to the nature of `json.RawMessage`. Why wouldn't it work?

**Comment by partomatl** [comment]
Sorry, I missed the `json.RawMessage` part of your example. It works well :)

I was wondering if we could add an `ECSLoggingModifierFunc` to this package, something like:
```go
func ECSLoggingModifierFunc(formatter ecslogrus.Formatter) func(entry *logrus.Entry, message *elogrus.Message) interface{} {
	return func(entry *logrus.Entry, message *elogrus.Message) interface{} {
		var data json.RawMessage
		var err error
		data, err = formatter.Format(entry)
		if err != nil {
			return entry
		}

		return data
	}
}
```

As a package that hooks `logrus` to Elastic using the official Go driver, it could made sense to add a feature to log in the recommended ECS logging format using the official Go ECS formatter.
Not sure it is a good idea though, considering that people might want to handle the formatting error in different ways.

**Comment by denisvmedia** [comment]
I'd avoid doing it in the package because it would add an extra dependency, and the ECS package seems to be not actively maintained. But Including this snippet in the docs might make sense.

**Comment by denisvmedia** [comment]
Thanks for your suggestions and feedback @partomatl. I guess it's now done and can be closed.
